### ISSUE TITLE
more user behaviour or relink the fork or point link with wallace pos

### ISSUE THREAD

**Issue by mckaygerhard** [h5gs/NativePOSEngineold#1]
more user behaviour or relink the fork or point link with wallace pos

## Context

Keep in mind that people who develop in the POS system is because they use it ... What happened when you no longer used a function? it will be the same behavior as opensourcepos .. (those guys always mention that they only work on their own features .. and argue that each person should make a request with code) - **many good people who do not have good coding skills are unable to code in complicated scenarios ... but you have a great idea and minimal code skill to do it in an ugly way. we have to take these users into account**

I try to make **an example with @ andriux1990 which has a good fork & huge improved version of opensourcepos with fiscal printer support (latin america) and credit debt .. (my special contributions for him)** moslty so used features but not present in most of the FOSS POS systems 

## Process

1. User make a new featured very used. you guys added of course (after a big time passed in coding requisites hell for that user)
2. Developers make new code and changes many things.. that feartured so used now is broken.. and we have some issues.. but not so many as others.. take in consideratin that users has no technicall skills to use github neither git
3. Feature is deleted or removed and new pos system are in same way as wallacepos or opensouorcepos.. 

## Expected result

1. relink the wallace pos.. to be more in sense with original author and pointed to users that we have a great base that always get support to..  you can mantain the new name of course!
2. make letter of conduct that prefers functionality over the quality of code, but without let alone quality of code, we need to make more assistance to users that have lack of skills in coding.. 
3. make a way to report issues more friendly .. designed a user that attent the issues and organized.. 

## justification

1. we need to link wallacepos because there are already some users in use, if the continuation is not on the way .. the history will always be the same .. _ "oh, look at another new fork .. sure after a year it will be abandoned and the new one version will fork .. puff again "_ 

2. I observed as example that the issue template asks a lot of technical questions. we need to reduce a be more friendly!

searching and looking at opensourcepos problems .. lots of end users and lack of coding users .. sorry but we need to get a good user code base ..

so we need a person to help new users who report problems ... if a user simply posts "I have a problem", of course they have no information ... so a designed user should put: 1) a tag with "needs information" That is not the same as "needs feedback", some questions to ask if the user does not understand!

also linking as fork with different name permits two things: 
* that users put their trust in free software by seeing that the same project continues 
* that the original author joins or make more attention after a time passed

**Comment by h5gs** [comment]
Agreed with your inputs , here is the linked one :) https://github.com/h5gs/NativePOSEngine

**Comment by mckaygerhard** [comment]
let this input open.. i try to tell to @andriux1990 to join the project

**Comment by mckaygerhard** [comment]
arrgggg @h5gs  forked project cannot have issues enabled?

**Comment by mckaygerhard** [comment]
ok i checked.. must read now #3  for the new location
