### ISSUE TITLE
[bug] issues are private, please made public to others to contribute

### ISSUE THREAD

**Issue by mckaygerhard** [h5gs/NativePOSEngineold#3]
i parse the project to some guys to property get collaboration, and gort this:

![imagen](https://user-images.githubusercontent.com/1571724/134529114-ac1d5153-e6d9-4740-bdea-2a033b6f30d1.png)

## Context

issues seems are private or disabled!

## Process

parte the link to issues and got a response of disabled or there's nothing

## Expected result

other people can issued new issues

## Current result

users cannot see my issues or make new ones

## Possible Fix

i dont know , please help me @h5gs

**Comment by mckaygerhard** [comment]
ok got it.. you done the #1 but still need to enable the issues in settings of the new location project

**Comment by mckaygerhard** [comment]
still need to enable the issues in settings of the new location project, thanks in advance..

**Comment by h5gs** [comment]
Thanks for your response.
I have enabled issues and discussion in that forked repo.

**Comment by mckaygerhard** [comment]
thanks.. @h5gs  now close dthis and ready to erased ththis repo
